// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/vkhrushchev/GophKeeper/internal/server/domain"
	entity "github.com/vkhrushchev/GophKeeper/internal/server/entity"
)

// MockPasswordHashCalculator is a mock of PasswordHashCalculator interface.
type MockPasswordHashCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHashCalculatorMockRecorder
}

// MockPasswordHashCalculatorMockRecorder is the mock recorder for MockPasswordHashCalculator.
type MockPasswordHashCalculatorMockRecorder struct {
	mock *MockPasswordHashCalculator
}

// NewMockPasswordHashCalculator creates a new mock instance.
func NewMockPasswordHashCalculator(ctrl *gomock.Controller) *MockPasswordHashCalculator {
	mock := &MockPasswordHashCalculator{ctrl: ctrl}
	mock.recorder = &MockPasswordHashCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHashCalculator) EXPECT() *MockPasswordHashCalculatorMockRecorder {
	return m.recorder
}

// CalculateHash mocks base method.
func (m *MockPasswordHashCalculator) CalculateHash(password string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateHash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CalculateHash indicates an expected call of CalculateHash.
func (mr *MockPasswordHashCalculatorMockRecorder) CalculateHash(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateHash", reflect.TypeOf((*MockPasswordHashCalculator)(nil).CalculateHash), password)
}

// MockPasswordHashValidator is a mock of PasswordHashValidator interface.
type MockPasswordHashValidator struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHashValidatorMockRecorder
}

// MockPasswordHashValidatorMockRecorder is the mock recorder for MockPasswordHashValidator.
type MockPasswordHashValidatorMockRecorder struct {
	mock *MockPasswordHashValidator
}

// NewMockPasswordHashValidator creates a new mock instance.
func NewMockPasswordHashValidator(ctrl *gomock.Controller) *MockPasswordHashValidator {
	mock := &MockPasswordHashValidator{ctrl: ctrl}
	mock.recorder = &MockPasswordHashValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHashValidator) EXPECT() *MockPasswordHashValidatorMockRecorder {
	return m.recorder
}

// ValidateHash mocks base method.
func (m *MockPasswordHashValidator) ValidateHash(expectedHash, password, salt string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateHash", expectedHash, password, salt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateHash indicates an expected call of ValidateHash.
func (mr *MockPasswordHashValidatorMockRecorder) ValidateHash(expectedHash, password, salt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateHash", reflect.TypeOf((*MockPasswordHashValidator)(nil).ValidateHash), expectedHash, password, salt)
}

// MockUserSaver is a mock of UserSaver interface.
type MockUserSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUserSaverMockRecorder
}

// MockUserSaverMockRecorder is the mock recorder for MockUserSaver.
type MockUserSaverMockRecorder struct {
	mock *MockUserSaver
}

// NewMockUserSaver creates a new mock instance.
func NewMockUserSaver(ctrl *gomock.Controller) *MockUserSaver {
	mock := &MockUserSaver{ctrl: ctrl}
	mock.recorder = &MockUserSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSaver) EXPECT() *MockUserSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockUserSaver) Save(ctx context.Context, userEntity entity.User) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userEntity)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserSaverMockRecorder) Save(ctx, userEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserSaver)(nil).Save), ctx, userEntity)
}

// MockUserProvider is a mock of UserProvider interface.
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider.
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance.
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserProvider) Get(ctx context.Context, username string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, username)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserProviderMockRecorder) Get(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserProvider)(nil).Get), ctx, username)
}

// MockTokenProvider is a mock of TokenProvider interface.
type MockTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderMockRecorder
}

// MockTokenProviderMockRecorder is the mock recorder for MockTokenProvider.
type MockTokenProviderMockRecorder struct {
	mock *MockTokenProvider
}

// NewMockTokenProvider creates a new mock instance.
func NewMockTokenProvider(ctrl *gomock.Controller) *MockTokenProvider {
	mock := &MockTokenProvider{ctrl: ctrl}
	mock.recorder = &MockTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProvider) EXPECT() *MockTokenProviderMockRecorder {
	return m.recorder
}

// ProvideToken mocks base method.
func (m *MockTokenProvider) ProvideToken(ctx context.Context, user domain.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvideToken", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvideToken indicates an expected call of ProvideToken.
func (mr *MockTokenProviderMockRecorder) ProvideToken(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideToken", reflect.TypeOf((*MockTokenProvider)(nil).ProvideToken), ctx, user)
}

// MockTokenInvalidator is a mock of TokenInvalidator interface.
type MockTokenInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenInvalidatorMockRecorder
}

// MockTokenInvalidatorMockRecorder is the mock recorder for MockTokenInvalidator.
type MockTokenInvalidatorMockRecorder struct {
	mock *MockTokenInvalidator
}

// NewMockTokenInvalidator creates a new mock instance.
func NewMockTokenInvalidator(ctrl *gomock.Controller) *MockTokenInvalidator {
	mock := &MockTokenInvalidator{ctrl: ctrl}
	mock.recorder = &MockTokenInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenInvalidator) EXPECT() *MockTokenInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateToken mocks base method.
func (m *MockTokenInvalidator) InvalidateToken(ctx context.Context, user domain.User, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateToken", ctx, user, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateToken indicates an expected call of InvalidateToken.
func (mr *MockTokenInvalidatorMockRecorder) InvalidateToken(ctx, user, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateToken", reflect.TypeOf((*MockTokenInvalidator)(nil).InvalidateToken), ctx, user, token)
}
